# -*- Makefile -*-

targets:=gcc.riscv64gc gcc.riscv64gcv
# clang.riscv64 gcc.native gcc.riscv64 gcc.native
executables:=$(foreach t,$(targets),$(benchmark).$(t))

gpp_native=g++ -std=gnu++2b
gpp_riscv=riscv64-unknown-linux-gnu-g++ -std=gnu++2b
gcc_riscv=riscv64-unknown-linux-gnu-gcc -std=gnu23
clang=clang++

flags_common=-Wall -O3 -ffast-math -static -I../common -g
flags_riscv=-mabi=lp64d # not really necessary 

deps_common=../common/g4tracer-interface.h

all: $(executables)

clean:
	rm -f $(executables) $(foreach e,$(executables),$(e).objdump)

%.gcc.native: %.cpp $(deps_common)
	$(gpp_native) $(flags_common) $< -o $@

%.gcc.riscv64: %.cpp $(deps_common)
	$(gpp_riscv) $(flags_common) $(flags_riscv) $< -o $@

%.gcc.riscv64gc: %.cpp $(deps_common)
	$(gpp_riscv) $(flags_common) $(flags_riscv) -march=rv64gc $< -o $@

%.gcc.riscv64gcv: %.cpp $(deps_common)
	$(gpp_riscv) $(flags_common) $(flags_riscv) -march=rv64gcv $< -o $@

%.gcc.riscv64gc: %.c $(deps_common)
	$(gcc_riscv) $(flags_common) $(flags_riscv) -march=rv64gc $< -o $@

%.gcc.riscv64gcv: %.c $(deps_common)
	$(gcc_riscv) $(flags_common) $(flags_riscv) -march=rv64gcv $< -o $@

%.clang.riscv64: %.cpp  $(deps_common) # TODO
	$(clang) --target=riscv64-linux-gnu --gcc-toolchain=… --sysroot=… $(flags_common) $< -o $@

%.objdump: %
	riscv64-unknown-linux-gnu-objdump -S $< > $@
