#!/bin/bash
SCRIPT_DIR="$(dirname "$(realpath "$0")")"
SCRIPT_COMMAND="$0"
set -o nounset
set -o pipefail
set -o errexit
trap 'echo "$SCRIPT_COMMAND: error $? at line $LINENO"' ERR

out_dir="${1:-outs}"

trace-all() {
    for b in "${benchmarks[@]}" ; do
        for v in "${versions[@]}" ; do
            ( cd "$b" ; rm -f "$b.$v.objdump.xz" ; make "$b.$v.objdump" )
            ( xz -9e "$b/$b.$v.objdump" ; mv "$b/$b.$v.objdump.xz" "${out_dir}/" ) &
            "${SCRIPT_DIR}/../spike-run-fs" \
                --spike="${SCRIPT_DIR}/../build/spike" \
                --num-procs=$(($procs + 1)) \
                -s--log-g4trace \
                -s--log-g4trace-dest="${out_dir}/$b.$v" \
                -- "$b/$b.$v"
        done
    done
}

mkdir "${out_dir}"

benchmarks=(test00)
versions=(riscv64gcv)
procs=1
trace-all

benchmarks=(test01 test02 test03 test04 test05 test06)
versions=(gcc.riscv64gc gcc.riscv64gcv)
procs=1
trace-all

benchmarks=(a01-far-atomic-friendly a02-near-atomic-friendly)
versions=(gcc.riscv64gcv)
procs=4
trace-all

wait
